version: "3"
services:
  db:
    image: mysql:latest
    container_name: application-challenge-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_USER_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: application-challenge-phpmyadmin
    restart: always
    ports:
      - 8889:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_USER_PASSWORD}"
    networks:
      - back
networks:
  back:
